# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'iOS-Base-Library' do
	pod 'Alamofire', '~> 3.1.5'
    pod 'CocoaLumberjack/Swift', '~> 2.2.0'
    pod 'UIColor_Hex_Swift', '~> 1.8'
    pod 'Device', '~> 0.0.6'
end