name: pull-request

on:
  pull_request:
    branches: [ master, main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build SPM
      run: |
        swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"
        
  danger:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
  
    - name: Run Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
