name: release

on:
  pull_request:
    branches: [ master, main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build SPM
      run: |
        swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"
        
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export RELEASE_VERSION="$(git describe --abbrev=0 | tr -d '\n')"
        pod repo push https://github.com/TouchInstinct/Podspecs ./TITransitions/TITransitions.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
